
#ifndef NTI_PROJECT_FUNCTIONS_PROTOTYPES_INTERRUPT_PROTOTYPES_H_
#define NTI_PROJECT_FUNCTIONS_PROTOTYPES_INTERRUPT_PROTOTYPES_H_

void interrupt_Init ();

#endif /* NTI_PROJECT_FUNCTIONS_PROTOTYPES_INTERRUPT_PROTOTYPES_H_ */
