
#ifndef NTI_PROJECT_FUNCTIONS_PROTOTYPES_TOSTRINGFUNCTION_PROTOTYPEST_H_
#define NTI_PROJECT_FUNCTIONS_PROTOTYPES_TOSTRINGFUNCTION_PROTOTYPEST_H_
#include "../DataTypes/Data_Types.h"

void toString( u16 num, u8* str, u8 dispSize );

#endif /* NTI_PROJECT_FUNCTIONS_PROTOTYPES_TOSTRINGFUNCTION_PROTOTYPEST_H_ */
