
#ifndef NTI_PROJECT_FUNCTIONS_PROTOTYPES_AUTOPARKING_PROTOTYPES_H_
#define NTI_PROJECT_FUNCTIONS_PROTOTYPES_AUTOPARKING_PROTOTYPES_H_
#include "../DataTypes/Data_Types.h"

void Calculate_vid_D( u32 uSonic_Read );

#endif /* NTI_PROJECT_FUNCTIONS_PROTOTYPES_AUTOPARKING_PROTOTYPES_H_ */
